language: java
jobs:
  include:
    - name: keycloak-javaee-example
      env: DIR=keycloak-javaee-example
    - name: ldap-keycloak-etl
      env: DIR=ldap-keycloak-etl
script: cd $DIR && mvn test -B
